### ISSUE TITLE
1.20.6 Doesnt display inventory

### ISSUE THREAD

**Issue by Jack-Chronicle** [MisterPeModder/ShulkerBoxTooltip#153] opened 2024-05-22 11:30 UTC
I'm not able to see the Shulkers inventory in the tooltip
When pressing Left Shift or Left Shift + Alt, I'm not seeing any image of the shulkers inventory, just the "Lock Tooltip"
Tried changing the settings to always display but that didn't change anything

____

- ShulkerBoxTooltip: 4.1.0-alpha.1+1.20.6
- Minecraft: 1.20.6
- Fabric Loader: 0.15.11
- Fabric API: 0.99.0+1.20.6

https://pastebin.com/t3MP02Fe

**Comment by Jack-Chronicle** [comment] 2024-05-24 11:29
Seems it was a mistake on my end, found an API mod for an app I don't use anymore I forgot to remove
Wasn't displaying because of Kaleido, worked fine after I removed it

**Comment by MisterPeModder** [comment] 2024-05-25 19:51
Hello, I'm closing this issue since this is not caused by ShulkerBoxTooltip.

**Closed as completed by MisterPeModder** 2024-05-25 19:51 UTC
Labels: Bug, Fabric
