### ISSUE TITLE
Request : Support Carpet AMS largeShulkerBox

### ISSUE THREAD

**Issue by Guerdi** [MisterPeModder/ShulkerBoxTooltip#142] opened 2023-12-17 16:06 UTC
The title is quite self-explanatory, currently the default size is always displayed even if objects are stored further than slot 26

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 4.0.3
- Minecraft: 1.20.1
- Carpet AMS: 2.18.0 (server-side only)

![2023-12-17_16 59 32](https://github.com/MisterPeModder/ShulkerBoxTooltip/assets/14162145/20859897-8834-4c79-98f5-8600a6e3ed6f)
![2023-12-17_16 59 43](https://github.com/MisterPeModder/ShulkerBoxTooltip/assets/14162145/850b6035-5062-4e51-b53e-a410ab627261)

**Comment by MisterPeModder** [comment] 2023-12-18 08:36
Hello, this is a duplicate of issue #140

**Closed as completed by MisterPeModder** 2023-12-18 08:36 UTC
Labels: Bug, duplicate
