### ISSUE TITLE
Rendering Issues

### ISSUE THREAD

**Issue by ZeburaBlack** [MisterPeModder/ShulkerBoxTooltip#45] opened 2021-03-12 15:26 UTC
#### Issue Description:

Tooltips refuse to acknowledge changes in mod menu or config. Colors do not change with dyes. Preview keys do not work.
This might have something to do with mod incompatibility, for there was a short window where Origins caused CTD with ShulkerBoxTooltips. Also unable to show tooltips for Upgraded Shulkers.

#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 2.3.5+1.16.5
- Minecraft: 1.16.5
- Fabric Loader: 0.11.2-1.16.5
- Fabric API: 0.32.0+1.16

#### Your most recent log file where the issue was present: 

[latest.log](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/6131023/latest.log)

**Comment by MisterPeModder** [comment] 2021-03-12 16:22
Do you have a link to the modpack you are using ?

**Comment by ZeburaBlack** [comment] 2021-03-12 17:39
https://www.dropbox.com/s/4q2vg90ce7he6va/EnchantmentCraftR6.zip?dl=1

Here it is, its a custom modpack so i dont have a list of all mods on hand.
This pack doesnt have tooltips in it, i was testing it as a possible addition.

**Comment by MisterPeModder** [comment] 2021-10-23 18:56
Closing this issue as it probably wasn't caused by SBTT

**Closed as completed by MisterPeModder** 2021-10-23 18:56 UTC
Labels: Bug
