### ISSUE TITLE
1.18.2 Fabric inmis/SBT Crash

### ISSUE THREAD

**Issue by PlayfulPiano** [MisterPeModder/ShulkerBoxTooltip#136] opened 2023-10-14 16:30 UTC
#### Issue Description:

Crash when mousing over a backpack from INMIS with SBT, while holding down shift.

#### What happens:
If you attempt to shift while mousing over an inmis backpack, the game crashes immediately.

#### What you expected to happen:
When mousing over an inmis backpack, while holding down shift, I should be able to see the contents of the backpack.

#### Steps to reproduce:

1. Have inmis and sbt installed.
2. Mouse over an inmis backpack while holding down shift.
____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: v3.4.1
- Minecraft: 1.18.2
- Fabric Loader: Quilt v0.21.0
- Fabric API: QFAPI v1.0.0 beta (fabric api v0.67.0 parity)
- Other mods (if relevant): inmis v2.6.0

#### Your most recent log file where the issue was present: 

[crash-2023-10-14_12.27.42-client.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/12906728/crash-2023-10-14_12.27.42-client.txt)
[2023-10-14-7.log.gz](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/12906733/2023-10-14-7.log.gz)

**Comment by MisterPeModder** [comment] 2023-10-30 23:15
Hi, sorry for the long delay.
The crash was caused by EquipmentCompare indirectly called a deprecated piece of code.
This should be resolved in the next patch,

**Closed as completed by MisterPeModder** 2023-10-30 23:15 UTC
Labels: Bug
