### ISSUE TITLE
When opening tooltip on a shulker box that has a long enough name where it takes up two lines, the tooltip is rendered below the first line and above the second line.

### ISSUE THREAD

**Issue by CalXee** [MisterPeModder/ShulkerBoxTooltip#67] opened 2021-10-19 14:24 UTC
#### Issue Description:

The tooltip is shown in between a long item name if it takes up multiple lines

#### What happens:

The tooltip is shown in between the first and second line of the shulker box name

#### What you expected to happen:

It should be shown below the last line of the name

#### Steps to reproduce:

1. Give a shulker box a very long name (use all 50 characters in 1.17)
2. Activate tooltip. Make sure the name takes up 2 lines; do so by making the name overlap with the edge of the screen.
3. Observe.
...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 3.0.1
- Minecraft: 1.17.1
- Fabric Loader: 0.11.7
- Fabric API: 41.0
- Other mods (if relevant): Possibly caused by this mod and "Tooltip Fix" https://www.curseforge.com/minecraft/mc-mods/tooltipfix

![2021-10-19_10 19 56](https://user-images.githubusercontent.com/68349758/137930283-f01d6ad3-15e8-4b7a-a05d-22a69cf93e06.png)

**Comment by MisterPeModder** [comment] 2021-10-23 16:31
This seems to be caused by tooltip fix, the author said the this is fixed in version 1.0.4, what version of tooltip fix are you currently running ?

**Comment by CalXee** [comment] 2021-11-30 20:14
Getting tooltip fix 1.0.4 (and port to 1.18) to see if this is fixed.

**Comment by CalXee** [comment] 2021-12-01 02:11
Not fixed with 1.18 Tooltip Fix 1.0.4 
![2021-11-30_21 10 33](https://user-images.githubusercontent.com/68349758/144159220-6e2c6c02-d54f-4d81-afd8-614fb799e826.png)
:(

**Comment by MisterPeModder** [comment] 2022-03-22 23:47
I still cannot reproduce this issue when running on Minecraft 1.18.2 with ToolTipFix 1.0.4.

Does this problem occur at different gui scales?
Have you tried to change the window position to 'Outside' in the configuration? (When modmenu is installed, `Mods` > `ShulkerBoxTooltip` > `Configure...` > `Preview` > `Window Position`).

#### GUI Scale 4
![2022-03-23_00 36 29](https://user-images.githubusercontent.com/7838479/159593585-c2f252ba-f41f-4043-bf9d-b0145452161e.png)

#### GUI Scale 3
![2022-03-23_00 38 02](https://user-images.githubusercontent.com/7838479/159593814-6857cf34-074e-4cc2-ac3d-ec340abc0994.png)

**Closed as not planned** 2022-09-12 08:04 UTC
Labels: Bug
