### ISSUE TITLE
Game Crashed when looking in shulkers

### ISSUE THREAD

**Issue by BaAssassin** [MisterPeModder/ShulkerBoxTooltip#78] opened 2022-04-17 03:50 UTC
#### Issue Description:

Games occasionally crashes when looking in shulkers in ender chest.

#### What happens:

^above

#### What you expected to happen:

the game to not crash

#### Steps to reproduce:

1. open enderchest
2. hover over shulker to look at contents
3. game crashed
...

____
#### Affected Versions (Do *not* use "latest"):

- ShulkerBoxTooltip: 3.0.7
- Minecraft: 1.18.2
- Fabric Loader: 0.13.3-1.18.2
- Fabric API: 0.48
- Other mods (if relevant): not sure other mods are causing issue, game only crashed with shulkerboxtooltip installed and when looking into shulkers

Crash Message:

The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "net.minecraft.class_1799.method_7909()" is null
Exit Code: -1

**Comment by MisterPeModder** [comment] 2022-04-19 13:31
Can you post your crash log? This would help me a lot!

**Comment by BaAssassin** [comment] 2022-04-26 14:51
[crash-2022-04-16_21.39.55-server.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/8564262/crash-2022-04-16_21.39.55-server.txt)

**Comment by MisterPeModder** [comment] 2022-05-04 09:31
Are you sure you sent me the right crash report? It looks like your game crashed due to a villager's inventory but it seems completely unrelated to ShulkerBoxTooltip, or even shulker boxes.

By chance, is the villager at (-216.30, 63.00, -739.70) in the overworld modified in any way?

**Comment by BaAssassin** [comment] 2022-05-04 11:57
I'm pretty sure that's the right crash report, the only crashes I've had have happened as described above. I shouldn't have any mods that effect villagers, just a resource pack for wandering traders. Those coords are the output of my villager breeder. I'll try to re-create the crash and post a crash report if i can.

**Comment by CAFRedblade** [comment] 2022-05-07 19:43
Hi MisterPeModder.  
Wanted to post as I've had two instances as well that time with crashing while looking at the contents of a shulker in the ender chest.   One time was near villagers, the other while in the nether.  Haven't been able to replicate it since the first two crashes though.  
[crash-2022-04-29_21.21.32-server.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/8645837/crash-2022-04-29_21.21.32-server.txt)
[crash-2022-04-30_23.50.45-server.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/8645838/crash-2022-04-30_23.50.45-server.txt)

Since then I've updated Xaeros Minimap and WorldMap mods to their latest version. 

Hope this helps.
Been enjoying the use of the Shulker Tooltip mod for several years now.  
Much appreciated.

**Comment by Kyle-Lancaster** [comment] 2022-05-09 17:08
Just want to add to this that I have been experiencing this exact issue. I was using this mod and experienced multiple crashes so I removed it and the crashes went away. I then started using this mod again for the last few days and I had a crash again today.

Here are all the crash reports that were generated:

[crash-2022-04-18_16.51.35-server.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/8653768/crash-2022-04-18_16.51.35-server.txt)
[crash-2022-04-26_19.32.07-server.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/8653769/crash-2022-04-26_19.32.07-server.txt)
[crash-2022-05-09_18.53.55-server.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/8653770/crash-2022-05-09_18.53.55-server.txt)
[crash-2022-04-17_12.07.52-server.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/8653771/crash-2022-04-17_12.07.52-server.txt)
[crash-2022-04-18_16.28.13-server.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/8653772/crash-2022-04-18_16.28.13-server.txt)
[crash-2022-04-18_16.38.45-server.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/8653773/crash-2022-04-18_16.38.45-server.txt)

These are all the mods I am running:

fabric-api-0.48.0+1.18.2.jar
lithium-fabric-mc1.18.2-0.7.9.jar
malilib-fabric-1.18.2-0.12.1.jar
minihud-fabric-1.18.2-0.22.0.jar
modmenu-3.1.0.jar
okzoomer-5.0.0-beta.5+1.18.2.jar
phosphor-fabric-mc1.18.x-0.8.1.jar
shulkerboxtooltip-3.0.7+1.18.2.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
worldedit-mod-7.2.10.jar

And using Fabric Loader 0.13.3-1.18.2

Hope this helps.

**Comment by MisterPeModder** [comment] 2022-05-14 13:54
Thanks @CAFRedblade and @Kyle-Lancaster for the logs, I'll look into it

**Comment by MisterPeModder** [comment] 2022-05-14 15:11
This is one heck of an issue, even sheep crashes the game!

Anyway, I believe I found the cause of the problem. The crashes might have been caused by item stacks that was shared between the SBTT previews and some entities.

I will release the potential fix on CF ASAP.

**Comment by MisterPeModder** [comment] 2022-05-14 15:22
The new release is up: https://www.curseforge.com/minecraft/mc-mods/shulkerboxtooltip/files/3790208

**Comment by Kyle-Lancaster** [comment] 2022-05-14 19:15
I just tried the updated file and, unfortunately, as soon as I hovered over the enderchest in my inventory the game crashed. Here is the report:

[Uploading crash-2022-05-14_21.12.38-server.txt…]()

**Comment by Kyle-Lancaster** [comment] 2022-05-14 19:17
For some reason the crash report did not upload properly, here it is:

[crash-2022-05-14_21.12.38-server.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/8693724/crash-2022-05-14_21.12.38-server.txt)

**Comment by MisterPeModder** [comment] 2022-05-14 20:23
The fact that simply looking at an ender chest in your inventory causes a *chicken* all of things to crash the whole server is simply mind-boggling....

Since I cannot reproduce these crashes at all, can you answer these questions?

Does the game crash:
* When hovering other containers, such as shulker boxes, or creative-picked chests?
* When the ender chest sync type in the config to "passive", or "none"?
* When you play on a different world? (maybe this is some kind or corruption)
* When playing on multiplayer?

You don't have to answer them all, but any will be greatly appreciated.

**Comment by Kyle-Lancaster** [comment] 2022-05-15 07:18
The problem with this crash is it is intermittent. I have been trying to make it crash but have not been able to again (a good thing?).

I will try to answer as many of your questions as possible but it might take a while.

To answer some of your questions now:

- Shulkerboxes have crashed for me in the past but the latest crashes are the enderchest.
- Enderchest sync type is "active", will try the other options
- I do not play multiplayer so will not be able to give feedback on that

**Comment by Kyle-Lancaster** [comment] 2022-05-15 07:24
Would you believe it, just after posting my previous reply it crashed.

I had Enderchest sync type set to "none" and when I hovered over a shulkerbox in my enderchest it crashed. I am on the same world as before.

[crash-2022-05-15_09.21.39-server.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/8694455/crash-2022-05-15_09.21.39-server.txt)

**Comment by MisterPeModder** [comment] 2022-05-16 09:25
The plot thickens...Thanks for you replies, that will help a lot!

**Comment by CAFRedblade** [comment] 2022-05-16 18:13
Haven't been able to replicate the bug yet, but thought I'd answer the below questions. 
Answers below:

 Does the game crash:

 * When hovering other containers, such as shulker boxes, or creative-picked chests?
It crashed while looking at shulker content, inside my enderchest.  
My Enderchest is filled with Shulker chests.

 * When the ender chest sync type in the config to "passive", or "none"?
Not sure, whatever the normal default would be. 

 * When you play on a different world? (maybe this is some kind or corruption)
Haven't seen it happen on any other world yet, but haven't been able to replicate it reliably on my main world either.

 * When playing on multiplayer?
Single player world

**Comment by BaAssassin** [comment] 2022-05-18 16:40
It seems like my most recent crash was due to ticking myself, not my villagers or another mob.


    When hovering other containers, such as shulker boxes, or creative-picked chests?
                Hovering over shulkers in the enderchest 99% hovering over shulker in inventory once.

    When the ender chest sync type in the config to "passive", or "none"?
                not sure

     When you play on a different world? (maybe this is some kind or corruption)
                 Not sure, haven't been able to reproduce.

     When playing on multiplayer?
                  Single player world (will still crash if I open it to LAN, don't play on multiplayer servers so I'm not sure about those

[crash-2022-05-18_10.33.08-server.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/8718284/crash-2022-05-18_10.33.08-server.txt)
)

**Comment by Heitzenberg** [comment] 2022-06-13 17:34
Has this been fixed in the 1.19 release?

**Comment by willrun4fun** [comment] 2022-06-14 16:02
It is still happening to me.

**Comment by Kyle-Lancaster** [comment] 2022-06-16 07:49
Just an update from me. I was previously playing in a single player world when the crashes occurred but about a month ago I set up a dedicated server for myslef in my house and transferred my single player world onto it. Since playing on this multiplayer (although it is just me) server I have never had a crash.

I have had this server running 1.18 and 1.19 on fabric.

Prehaps there is something strange with the mod on single player?

Anyway, thanks for this wonderful mod!

**Comment by willrun4fun** [comment] 2022-06-16 07:55
I was just curious that you showed you had Tweakaroo loaded.  Tweakaroo also has a shulker preview function so why use this mod at all?

**Comment by grindersSs** [comment] 2022-06-16 20:23
Also encountered this.
I noticed that this happens when I first enter the world and hover over the ender chest or shulker.
If then restore a copy of the world before the crash and load it without closing the launcher, then the crash does not occur.
[crash-2022-06-15_20.33.07-server.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/8922148/crash-2022-06-15_20.33.07-server.txt)
[crash-2022-06-16_21.50.15-server.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/8922149/crash-2022-06-16_21.50.15-server.txt)
[crash-2022-06-16_21.52.32-server.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/8922150/crash-2022-06-16_21.52.32-server.txt)
[crash-2022-06-16_21.55.50-server.txt](https://github.com/MisterPeModder/ShulkerBoxTooltip/files/8922151/crash-2022-06-16_21.55.50-server.txt)

**Closed as completed** 2022-07-02 02:47 UTC
Labels: Bug

**Comment by MisterPeModder** [comment] 2022-07-02 02:49
I finally managed to identify the cause of the random crashes, they should (hopefully) never occur again in the next releases of the mod.

Thank you so much everyone for posting your many logs, this helped a lot!

**Comment by MisterPeModder** [comment] 2022-07-02 02:57
By the way, the reason I previously could not reproduce the issue was because the bug was more likely to occur the laggier the world is. The more entities loaded, the more chances of a vanilla entity equipment check would occur exactly when the player opens a preview.
