### ISSUE TITLE
Im having trouble with initializing. Exit Code: -1

### ISSUE THREAD

**Issue by OWNEDGAMING** [MisterPeModder/ShulkerBoxTooltip#42] opened 2021-02-05 22:05 UTC
Im having the same trouble with the "[1.16.4, 1.16.5] ShulkerBoxTooltip-2.3.4+1.16.4" file and "[1.16.4] ShulkerBoxTooltip-2.3.3+1.16.4 file" i have no idea whats causing this since the other mods i have have worked together before.

**Mod list:** 
Auto Config Updated API. File; autoconfig1u-3.3.1.jar
Cloth Config API (Fabric). File; config-2-4.8.3.jar
VoxelMap. File; fabricmod_VoxelMap-1.10.14_for_1.16.4.jar
Mod Menu. File; modmenu-1.14.12+build.18.jar AND modmenu-1.16.5.jar
OptiFabric. File; optifabric-1.9.2.jar
OptiFine. File OptiFine_1.16.4_HD_U_G6.jar
ShulkerBoxTooltip. File; shulkerboxtooltip-2.3.4+1.16.4.jar AND shulkerboxtooltip-2.3.3+1.16.4.jar

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'shulkerboxtooltip'!
Exit Code: -1

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2/5/21 10:41 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'shulkerboxtooltip'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/network/ServerSidePacketRegistry
	at com.misterpemodder.shulkerboxtooltip.impl.network.client.C2SPacketType.register(C2SPacketType.java:19)
	at com.misterpemodder.shulkerboxtooltip.impl.network.client.C2SPacketTypes.register(C2SPacketTypes.java:10)
	at com.misterpemodder.shulkerboxtooltip.impl.ShulkerBoxTooltip.onInitialize(ShulkerBoxTooltip.java:61)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2246/633655968.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.network.ServerSidePacketRegistry
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1734282904 bytes (1653 MB) / 2080374784 bytes (1984 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.11.1-1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.16.4_HD_U_G6
	OptiFine Build: 20210117-001622
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 0

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.4
	OptiFine jar version: OptiFine_1.16.4_HD_U_G6
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:\Users\elev\AppData\Roaming\.minecraft\.optifine\OptiFine_1.16.4_HD_U_G6\Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by MisterPeModder** [comment] 2021-02-06 21:00
This is caused by newer versions of Fabric API having removed the old networking API.
This is already fixed in the 1.17 branch, I just need to backport this to the 1.16 one.

**Closed as completed** 2021-02-06 21:50 UTC
